############################
## CHANGE THESE
############################

baseURL: "https://ElTecnico89.github.io/qubtTheme"
title: qubtTheme

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
